version: "3.3"

services:
  client:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - node_backend
      - go_backend

  node_backend:
    build: ./nodejs
    depends_on:
      - redis
    deploy:
      replicas: 2

  go_backend:
    build: ./go
    depends_on:
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis
    restart: always
