version: "3.3"

services:
  client:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - node_backend
      - go_backend

  node_backend:
    build: ./nodejs
    ports:
      - 3000:3000
    depends_on:
      - redis

  go_backend:
    build: ./go
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
